// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrd6X7eFp2n0p89hhBqwM1Jsib5bFSSq8',
    appId: '1:818369900653:web:6001ec77e3fb8c88e00f64',
    messagingSenderId: '818369900653',
    projectId: 'pennywise-68115',
    authDomain: 'pennywise-68115.firebaseapp.com',
    storageBucket: 'pennywise-68115.firebasestorage.app',
    measurementId: 'G-FTJR2QCPC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbCe_WmMDjE9GtGtVqKNPzzDlRej8T89s',
    appId: '1:818369900653:android:01797a32bdec0a62e00f64',
    messagingSenderId: '818369900653',
    projectId: 'pennywise-68115',
    storageBucket: 'pennywise-68115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogXOUpwixFroe0b6fsrdjuC6Er25twds',
    appId: '1:818369900653:ios:400ba21b088456c4e00f64',
    messagingSenderId: '818369900653',
    projectId: 'pennywise-68115',
    storageBucket: 'pennywise-68115.firebasestorage.app',
    iosBundleId: 'com.example.pennywise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogXOUpwixFroe0b6fsrdjuC6Er25twds',
    appId: '1:818369900653:ios:400ba21b088456c4e00f64',
    messagingSenderId: '818369900653',
    projectId: 'pennywise-68115',
    storageBucket: 'pennywise-68115.firebasestorage.app',
    iosBundleId: 'com.example.pennywise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrd6X7eFp2n0p89hhBqwM1Jsib5bFSSq8',
    appId: '1:818369900653:web:667b7a0a2f4155d1e00f64',
    messagingSenderId: '818369900653',
    projectId: 'pennywise-68115',
    authDomain: 'pennywise-68115.firebaseapp.com',
    storageBucket: 'pennywise-68115.firebasestorage.app',
    measurementId: 'G-G4DPJ4GH0L',
  );
}
